sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t 11091992/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 11091992/react-test npm test

after_success:
    - docker build -t 11091992/multi-client ./client
    - docker build -t 11091992/multi-nginx ./nginx
    - docker build -t 11091992/multi-server ./server
    - docker build -t 11091992/multi-worker ./worker    
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push 11091992/multi-client
    - docker push 11091992/multi-nginx
    - docker push 11091992/multi-server
    - docker push 11091992/multi-worker